services:
  - type: web
    name: aura-vault
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_WGj69mIEwzNr@ep-green-base-an3n0aaq-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
